<?php

/**
 * @file
 * Demonstrates how to define a new configuration entity type.
 */

/**
 * @defgroup config_entity_example Example: Config Entity
 * @ingroup examples
 * @{
 * Implement a Config Entity.
 *
 * This module demonstrates implementing a Config Entity.
 *
 * This is an example of a simple configuration entity, the kind you might
 * create to store administrator-defined objects like blocks or views.
 *
 * In this module we define a configuration entity named 'Robot'. The entity
 * has a unique ID (also called a machine name), a human-readable label used
 * for display, and a universally unique identifier. You can create new robots
 * by navigating to &lt;your_site_root&gt;/examples/config_entity_example. A
 * default robot, "marvin", is included with the module.
 *
 * What's special about a Configuration Entity?
 *
 * Configuration entities are entities just like content entities. The key
 * difference is where the data is stored. Content entities are stored in the
 * database. Configuration entities are stored in *.yml files, typically under
 * &lt;your_site_root&gt;/sites/default/files/config_&lt;unique_id&gt;.
 *
 * Another key difference with configuration entities is the expectation they
 * are created by administrators, and not end users. As files, configuration
 * entities can be added to a version control system.
 *
 * Originally based on code from blog post at
 * http://previousnext.com.au/blog/understanding-drupal-8s-config-entities
 */

/**
 * @} End of "defgroup config_entity_example".
 */
define('AMAP_JS_KEY', 'cd09ada094d922e6129c7a1455e719be');
define('AMAP_JS_REST_API', 'https://webapi.amap.com/maps?v=1.4.1');
define('AMAP_UI_COMPONENTS', 'https://webapi.amap.com/ui/1.0/main.js');

/**
 * image file save path
 **/
define('HOTEL_IMAGE_PATH', '客栈图片信息/');
/**
 * Implement Hook_theme for wechat mobile
 **/
function wechat_mobile_theme($existing, $type, $theme, $path) {
    return array (
        'wechat_mobile_gen_tpl' => array(
            'variables' => array(
                'title' => null,
                'styles' => null,
                'scripts' => null,
                'page' => null
            )
        )
    );
}


