<?php

/**
 * @file
 * Contains wechat_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wechat_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wechat_rest module.
    case 'help.page.wechat_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('wechat rest service') . '</p>';
      return $output;

    default:
  }
}
