<?php

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 *
 * In this example, we log a message after the time given in the state value
 * 'cron_example.next_execution'. Then we update that variable to a time in the
 * future.
 */
function dld_wxapp_cron_cron() {

    $config = \Drupal::config('dld_wxapp_cron.settings');
    $interval = $config->get('interval');
    $lastrun = $config->get('LastRun');
    $item = array('interval' => $interval, 'lastrun' => $lastrun);
    //add queue to cron
    $queue = \Drupal::queue('cron_access_Token_queue');
    $queue->createItem($item);

}

/**
 * @} End of "dld_wxapp_cron_cron.module".
 */

